//
// Module lab6_lib.CONV.tbl
//
// Created:
//          by - maro4_000.UNKNOWN (LILY-PC)
//          at - 23:23:24 13.12.2019
//
// Generated by Mentor Graphics' HDL Designer(TM) 2018.2 (Build 19)
//

`resetall
`timescale 1ns/10ps
module CONV( 
   // Port Declarations
   input   wire    [3:0]  a, 
   output  reg     [7:0]  b
);


// Internal Declarations



// Local declarations
 

/////////////////////////////////////////////////////////////////
always @ (a) begin : truth_table_block_proc

   // Block 1
   case (a)
      4'b0000 :
         b = 8'b11000000;
      4'b0001 :
         b = 8'b11111001;
      4'b0010 :
         b = 8'b10100100;
      4'b0011 :
         b = 8'b10110000;
      4'b0100 :
         b = 8'b10011001;
      4'b0101 :
         b = 8'b10010010;
      4'b0110 :
         b = 8'b10000010;
      4'b0111 :
         b = 8'b11111000;
      4'b1000 :
         b = 8'b10000000;
      4'b1001 :
         b = 8'b10010000;
      4'b1010 :
         b = 8'b10001000;
      4'b1011 :
         b = 8'b10000011;
      4'b1100 :
         b = 8'b11000110;
      4'b1101 :
         b = 8'b10100001;
      4'b1110 :
         b = 8'b10000110;
      4'b1111 :
         b = 8'b10001110;
      default:
         ;
   endcase
end

endmodule // CONV

